### ISSUE TITLE
Collegamento mancante al programmino per la schwa

### ISSUE THREAD

**Issue by visika** [edmael/livellosegreto-bugtracker#1]
Sulla pagina https://livellosegreto.it/about/more alla penultima riga si fa riferimento a un programmino ma non c'è alcun riferimento in merito che sia riuscito a trovare.
Sto visualizzando la pagina da Firefox su Linux.

**Comment by edmael** [comment]
Sistemato!

Ho colto l'occasione per creare anche un sottodominio (per ora praticamente vuoto) così da avere un comodo schwa.livellosegreto.it per chi volesse condividere il software anche altrove.
