### ISSUE TITLE
Aggiungere link a progetti correlati nella pagina Info

### ISSUE THREAD

**Issue by giuseongit** [edmael/livellosegreto-bugtracker#8]
Ci sono un po' di progetti correlati all'istanza livellosegreto.it (ad esempio Warp, Radio e Quest), però è difficile venirne a conoscenza se non per puro caso, seguendo kenobit o qualcuon che periodicamente li pubblicizza.

Visto che fanno comunque parte di uno stesso gruppo di servizi, perchè non aggiungere alla pagina info del server tutte le istanze di altri software che sono correlate alla nostra istanza?

È abbastanza comune vedere la pagina info nel caso in cui si voglia informazioni aggiuntive riguardo l'istanza e un po' tutto il progetto livellosegreto, quindi credo sia utile avere un posto in cui chiunque possa vedere a colpo d'occhio altri servizi potenzialmente interessanti.

**Comment by edmael** [comment]
Sistemata la pagina about (https://livellosegreto.it/about) per includere tutti i link utili, grazie dell'ottima idea ;)
